# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:

- name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

- name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

- name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'composer', 'install']

- name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

- name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', 'artisan', 'key:generate']

- name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', 'artisan', 'migrate']

- name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']